import React from "react";

const CartContext = React.createContext({
  cartId: "",
  items: [],
  totalCCAmount: 0,
  totalIEFTAmount: 0,
  token: "",
  orderno: "",
  orderid: 0,
  isInsured: false,
  insAmount: 0,
  shippingAddress: {},
  paymentMode: "",
  ordernote: "",
  status: 0,
  discountPer: 0,
  discountAmt: 0,
  shippingCharge: 0,
  shippingCharge2: 0,
  shippingChargesAddOn: 0,
  isConfirmed: false,
  cartResp: { isRes: false, message: "", actionRes: false },
  addItem: (item) => {},
  removeItem: (id) => {},
  updateCarId: (id) => {},
  updateItem: (item) => {},
  setShippingAddress: (address, ordernote) => {},
  setInsurance: (isInsured, insuredAmt) => {},
  setOrderDetails: (orderid, orderno) => {},
  setPaymentMode: (paymode) => {},
  setDiscount: (discountAmt, discountPer) => {},
  setShippingCharges: (shipCharge, shipCharge2, shipChargeAddOn) => {},
  setStatus: (status) => {},
  emptyCart: () => {},
  setConfirmed: (confirmed) => {},
});

export default CartContext;
