import React from "react";

const NCartContext = React.createContext({
  sessId: "",
  items: [],
  totalCCAmount: 0,
  totalIEFTAmount: 0,
  orderno: "",
  isInsured: false,
  insAmount: 0,
  shippingAddress: {},
  paymentMode: "",
  ordernote: "",
  status: 0,
  discountPer: 0,
  discountAmt: 0,
  shippingCharge: 0,
  shippingCharge2: 0,
  shippingChargesAddOn: 0,
  isConfirmed: false,
  isTVLicence: false,
  isValidLicence: false,
  tvLicenceNo: "",
  tvLicenceType: "",
  tvLicenceResp: null,
  addItem: (item) => {},
  removeItem: (id) => {},
  updateItem: (item) => {},
  setShippingAddress: (address, ordernote) => {},
  setInsurance: (isInsured, insuredAmt) => {},
  setPaymentMode: (paymode) => {},
  setDiscount: (discountAmt, discountPer) => {},
  setShippingCharges: (shipCharge, shipCharge2, shipChargeAddOn) => {},
  setStatus: (status) => {},
  fetchCart: () => {},
  emptyCart: () => {},
  setConfirmed: (confirmed) => {},
  setOrderDetails: (orderid, orderno) => {},
  setPromoCode: (promocode) => {},
});

export default NCartContext;
