"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProps } from "next/app";
import "@/styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-bootstrap-typeahead/css/Typeahead.css";
import "react-image-gallery/styles/css/image-gallery.css";
import AuthProvider from "@/store/AuthProvider";
import HeaderProvider from "@/store/HeaderProvider";
import HelperProvider from "@/store/HelperProvider";
import NCartProvider from "@/store/NCartProvider";
import { Structure } from "@components";

// import Main from "@/pages/_main";
import Head from "next/head";
import { ThemeProvider, useTheme } from "@/store/ThemeContext";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <AuthProvider>
        <HeaderProvider>
          <HelperProvider>
            <NCartProvider>
              <ThemeProvider>
                <Structure
                >
                  {children}
                </Structure>
              </ThemeProvider>
            </NCartProvider>
          </HelperProvider>
        </HeaderProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
