"use client";
// import type { Metadata } from "next";
import { Inter } from "next/font/google";
import { AppProps } from "next/app";
import "@/styles/globals.scss";
import "bootstrap/dist/css/bootstrap.min.css";
import "react-bootstrap-typeahead/css/Typeahead.css";
import "react-image-gallery/styles/css/image-gallery.css";
import AuthProvider from "@/store/AuthProvider";
import HeaderProvider from "@/store/HeaderProvider";
import HelperProvider from "@/store/HelperProvider";
import NCartProvider from "@/store/NCartProvider";
import { Structure } from "@components";

// import Main from "@/pages/_main";
import Head from "next/head";
import { ThemeProvider, useTheme } from "@/store/ThemeContext";


const inter = Inter({ subsets: ["latin"] });

// export const metadata: Metadata = {
//   title: "Create Next App",
//   description: "Generated by create next app",
// };

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
        <title itemProp="name" lang="en">
          Evetech Custom Computer Systems, Gaming Computers, Desktops Gaming PCs
        </title>
        <link rel="icon" href="https://evetech.co.za/icons/favicon-32x32.png" />
        <title itemProp="name" lang="en">
          Evetech Custom Computer Systems, Gaming Computers, Desktops Gaming PCs
        </title>
        <link rel="canonical" href="https://www.evetech.co.za/" />
        <meta
          name="description"
          content="Gaming Pc's, Custom Built Cheap Gaming Computer Systems, The lastest Gaming PC Systems, Intel i7 PC Gaming Desktops. Configure your own Gaming Pc Here!"
        />
        <meta
          name="keywords"
          content="gaming pc,gaming computers,cheap gaming pc,intel core i7,custom gaming computers,custom gaming pc"
        />
      <body className={inter.className}>
        <AuthProvider>
        <HeaderProvider>
          <HelperProvider>
            <NCartProvider>
              <ThemeProvider>
                <Structure
                >
                  {children}
                </Structure>
              </ThemeProvider>
            </NCartProvider>
          </HelperProvider>
        </HeaderProvider>
      </AuthProvider>
      </body>
    </html>
  );
}
